const basketballPlayers = [
    // --- EASY (Superstars / Global Icons) ---
    { name: "LeBron James", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2003-2010", team: "Cleveland Cavaliers" }, { years: "2010-2014", team: "Miami Heat" }, { years: "2014-2018", team: "Cleveland Cavaliers" }, { years: "2018-Present", team: "LA Lakers" }] },
    { name: "Stephen Curry", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2009-Present", team: "Golden State Warriors" }] },
    { name: "Kevin Durant", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2007-2016", team: "OKC Thunder" }, { years: "2016-2019", team: "Golden State Warriors" }, { years: "2019-2022", team: "Brooklyn Nets" }, { years: "2022-Present", team: "Phoenix Suns" }] },
    { name: "Giannis Antetokounmpo", difficulty: "easy", status: "active", position: "Forvet", flag: "🇬🇷", nationality: "Yunanistan", career: [{ years: "2013-Present", team: "Milwaukee Bucks" }] },
    { name: "Nikola Jokic", difficulty: "easy", status: "active", position: "Pivot", flag: "🇷🇸", nationality: "Sırbistan", career: [{ years: "2012-2015", team: "Mega Basket" }, { years: "2015-Present", team: "Denver Nuggets" }] },
    { name: "Luka Doncic", difficulty: "easy", status: "active", position: "Guard", flag: "🇸🇮", nationality: "Slovenya", career: [{ years: "2015-2018", team: "Real Madrid" }, { years: "2018-Present", team: "Dallas Mavericks" }] },
    { name: "Joel Embiid", difficulty: "easy", status: "active", position: "Pivot", flag: "🇨🇲", nationality: "Kamerun", career: [{ years: "2014-Present", team: "Philadelphia 76ers" }] },
    { name: "Jayson Tatum", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2017-Present", team: "Boston Celtics" }] },
    { name: "Shai Gilgeous-Alexander", difficulty: "easy", status: "active", position: "Guard", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "2019-Present", team: "OKC Thunder" }] },
    { name: "Anthony Edwards", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2020-Present", team: "Minnesota Timberwolves" }] },
    { name: "Victor Wembanyama", difficulty: "easy", status: "active", position: "Pivot", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2021-2022", team: "ASVEL" }, { years: "2022-2023", team: "Metropolitans 92" }, { years: "2023-Present", team: "San Antonio Spurs" }] },
    { name: "Kyrie Irving", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2011-2017", team: "Cleveland Cavaliers" }, { years: "2017-2019", team: "Boston Celtics" }, { years: "2019-2023", team: "Brooklyn Nets" }, { years: "2023-Present", team: "Dallas Mavericks" }] },
    { name: "James Harden", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2012-2021", team: "Houston Rockets" }, { years: "2021-2022", team: "Brooklyn Nets" }, { years: "2022-2023", team: "Philadelphia 76ers" }, { years: "2023-Present", team: "LA Clippers" }] },
    { name: "Damian Lillard", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2012-2023", team: "Portland Trail Blazers" }, { years: "2023-Present", team: "Milwaukee Bucks" }] },
    { name: "Anthony Davis", difficulty: "easy", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2012-2019", team: "New Orleans Pelicans" }, { years: "2019-Present", team: "LA Lakers" }] },
    { name: "Michael Jordan", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1984-1998", team: "Chicago Bulls" }] },
    { name: "Kobe Bryant", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1996-2016", team: "LA Lakers" }] },
    { name: "Shaquille O'Neal", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1992-2011", team: "Lakers/Magic/Heat" }] },
    { name: "Magic Johnson", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1979-1991", team: "LA Lakers" }] },
    { name: "Larry Bird", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1979-1992", team: "Boston Celtics" }] },
    { name: "Kareem Abdul-Jabbar", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1969-1989", team: "Lakers/Bucks" }] },
    { name: "Wilt Chamberlain", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1959-1973", team: "Warriors/76ers/Lakers" }] },
    { name: "Bill Russell", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1956-1969", team: "Boston Celtics" }] },
    { name: "Tim Duncan", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1997-2016", team: "San Antonio Spurs" }] },
    { name: "Dirk Nowitzki", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇩🇪", nationality: "Almanya", career: [{ years: "1998-2019", team: "Dallas Mavericks" }] },
    { name: "Dwyane Wade", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2003-2019", team: "Miami Heat" }] },
    { name: "Hakeem Olajuwon", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1984-2002", team: "Houston Rockets" }] },
    { name: "Charles Barkley", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1984-2000", team: "Suns/76ers/Rockets" }] },
    { name: "John Stockton", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1984-2003", team: "Utah Jazz" }] },
    { name: "Karl Malone", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1985-2004", team: "Utah Jazz" }] },
    { name: "Derrick Rose", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2008-2024", team: "Bulls/Knicks/Grizzlies" }] },
    { name: "Kawhi Leonard", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2011-2018", team: "San Antonio Spurs" }, { years: "2018-2019", team: "Toronto Raptors" }, { years: "2019-Present", team: "LA Clippers" }] },
    { name: "Paul George", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2010-2017", team: "Indiana Pacers" }, { years: "2017-2019", team: "OKC Thunder" }, { years: "2019-2024", team: "LA Clippers" }, { years: "2024-Present", team: "Philadelphia 76ers" }] },
    { name: "Jimmy Butler", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2011-2017", team: "Chicago Bulls" }, { years: "2017-2018", team: "Minnesota Timberwolves" }, { years: "2018-2019", team: "Philadelphia 76ers" }, { years: "2019-Present", team: "Miami Heat" }] },
    { name: "Devin Booker", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2015-Present", team: "Phoenix Suns" }] },
    { name: "Donovan Mitchell", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2017-2022", team: "Utah Jazz" }, { years: "2022-Present", team: "Cleveland Cavaliers" }] },
    { name: "Ja Morant", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2019-Present", team: "Memphis Grizzlies" }] },
    { name: "Zion Williamson", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2019-Present", team: "New Orleans Pelicans" }] },
    { name: "Trae Young", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2018-Present", team: "Atlanta Hawks" }] },
    { name: "Tyrese Haliburton", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2020-Present", team: "Indiana Pacers" }] },
    { name: "Jaylen Brown", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2016-Present", team: "Boston Celtics" }] },
    { name: "De'Aaron Fox", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2017-Present", team: "Sacramento Kings" }] },
    { name: "Bam Adebayo", difficulty: "easy", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2017-Present", team: "Miami Heat" }] },
    { name: "Domantas Sabonis", difficulty: "easy", status: "active", position: "Pivot", flag: "🇱🇹", nationality: "Litvanya", career: [{ years: "2012-2014", team: "Unicaja" }, { years: "2016-2017", team: "OKC Thunder" }, { years: "2017-2022", team: "Indiana Pacers" }, { years: "2022-Present", team: "Sacramento Kings" }] },
    { name: "Lauri Markkanen", difficulty: "easy", status: "active", position: "Forvet", flag: "🇫🇮", nationality: "Finlandiya", career: [{ years: "2017-2021", team: "Chicago Bulls" }, { years: "2021-2022", team: "Cleveland Cavaliers" }, { years: "2022-Present", team: "Utah Jazz" }] },
    { name: "Kristaps Porzingis", difficulty: "easy", status: "active", position: "Pivot", flag: "🇱🇻", nationality: "Letonya", career: [{ years: "2015-Present", team: "Celtics/Mavs/Knicks" }] },
    { name: "Pascal Siakam", difficulty: "easy", status: "active", position: "Forvet", flag: "🇨🇲", nationality: "Kamerun", career: [{ years: "2016-Present", team: "Pacers/Raptors" }] },
    { name: "Jamal Murray", difficulty: "easy", status: "active", position: "Guard", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "2016-Present", team: "Denver Nuggets" }] },
    { name: "Karl-Anthony Towns", difficulty: "easy", status: "active", position: "Pivot", flag: "🇩🇴", nationality: "Dominik Cum.", career: [{ years: "2015-2024", team: "Minnesota Timberwolves" }, { years: "2024-Present", team: "New York Knicks" }] },
    { name: "Rudy Gobert", difficulty: "easy", status: "active", position: "Pivot", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2013-Present", team: "Wolves/Jazz" }] },

    // --- MEDIUM (All-Stars / Strong Starters / Icons) ---
    // --- EASY (Active Superstars & Legend Icons) ---
    { name: "Manu Ginobili", difficulty: "easy", status: "retired", position: "Guard", flag: "🇦🇷", nationality: "Arjantin", career: [{ years: "2002-2018", team: "San Antonio Spurs" }] },
    { name: "Tony Parker", difficulty: "easy", status: "retired", position: "Guard", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2001-2019", team: "San Antonio Spurs" }] },
    { name: "Pau Gasol", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇪🇸", nationality: "İspanya", career: [{ years: "2001-2019", team: "Lakers/Grizzlies" }] },
    { name: "Chris Bosh", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2003-2016", team: "Heat/Raptors" }] },
    { name: "Ray Allen", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1996-2014", team: "Celtics/Bucks/Heat" }] },
    { name: "Paul Pierce", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1998-2017", team: "Boston Celtics" }] },
    { name: "Kevin Garnett", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1995-2016", team: "Wolves/Celtics" }] },
    { name: "Vince Carter", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1998-2020", team: "Raptors/Nets/Hawks" }] },
    { name: "Tracy McGrady", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1997-2013", team: "Rockets/Magic/Raptors" }] },
    { name: "Carmelo Anthony", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2003-2022", team: "Knicks/Nuggets/Lakers" }] },
    { name: "Steve Nash", difficulty: "easy", status: "retired", position: "Guard", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "1996-2014", team: "Suns/Mavs/Lakers" }] },
    { name: "Jason Kidd", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1994-2013", team: "Nets/Mavs/Suns" }] },
    { name: "Reggie Miller", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1987-2005", team: "Indiana Pacers" }] },
    { name: "Gary Payton", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1990-2007", team: "Seattle SuperSonics" }] },
    { name: "Shawn Kemp", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1989-2003", team: "Seattle SuperSonics" }] },
    { name: "Chris Webber", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1993-2008", team: "Kings/Wizards/Warriors" }] },
    { name: "Grant Hill", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1994-2013", team: "Pistons/Magic/Suns" }] },
    { name: "Penny Hardaway", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1993-2007", team: "Magic/Suns" }] },
    { name: "Yao Ming", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇨🇳", nationality: "Çin", career: [{ years: "2002-2011", team: "Houston Rockets" }] },
    { name: "Dikembe Mutombo", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇨🇩", nationality: "Kongo", career: [{ years: "1991-2009", team: "Nuggets/Hawks/Rockets" }] },
    { name: "Alonzo Mourning", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1992-2008", team: "Miami Heat" }] },
    { name: "Clyde Drexler", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1983-1998", team: "Blazers/Rockets" }] },
    { name: "Isiah Thomas", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1981-1994", team: "Detroit Pistons" }] },
    { name: "Dominique Wilkins", difficulty: "easy", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1982-1999", team: "Atlanta Hawks" }] },
    { name: "Patrick Ewing", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇯🇲", nationality: "Jamaika", career: [{ years: "1985-2002", team: "New York Knicks" }] },
    { name: "David Robinson", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1989-2003", team: "San Antonio Spurs" }] },
    { name: "Kyle Lowry", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2006-Present", team: "Raptors/Heat/76ers" }] },
    { name: "DeMar DeRozan", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2009-Present", team: "Raptors/Spurs/Bulls/Kings" }] },
    { name: "Jalen Brunson", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2018-Present", team: "Knicks/Mavs" }] },
    { name: "Bradley Beal", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2012-Present", team: "Suns/Wizards" }] },
    { name: "Chet Holmgren", difficulty: "easy", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2022-Present", team: "OKC Thunder" }] },
    { name: "Paolo Banchero", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2022-Present", team: "Orlando Magic" }] },
    { name: "Scottie Barnes", difficulty: "easy", status: "active", position: "Forvet", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "2021-Present", team: "Toronto Raptors" }] },
    { name: "Tyrese Maxey", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2020-Present", team: "Philadelphia 76ers" }] },
    { name: "Evan Mobley", difficulty: "easy", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2021-Present", team: "Cleveland Cavaliers" }] },
    { name: "Darius Garland", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2019-Present", team: "Cleveland Cavaliers" }] },
    { name: "Cade Cunningham", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2021-Present", team: "Detroit Pistons" }] },
    { name: "Brandon Ingram", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2016-Present", team: "Pelicans/Lakers" }] },
    { name: "CJ McCollum", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2013-Present", team: "Pelicans/Blazers" }] },
    { name: "Klay Thompson", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2011-2024", team: "Golden State Warriors" }, { years: "2024-Present", team: "Dallas Mavericks" }] },
    { name: "Draymond Green", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2012-Present", team: "Golden State Warriors" }] },
    { name: "Andrew Wiggins", difficulty: "easy", status: "active", position: "Forvet", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "2014-Present", team: "Warriors/Wolves" }] },
    { name: "Julius Randle", difficulty: "easy", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2014-Present", team: "Wolves/Knicks/Lakers" }] },
    { name: "Zach LaVine", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2014-2017", team: "Minnesota Timberwolves" }, { years: "2017-Present", team: "Chicago Bulls" }] },

    // --- HARD (Supporting Stars & NBA Icons) ---
    { name: "John Wall", difficulty: "hard", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2010-2023", team: "Washington Wizards" }] },
    { name: "Blake Griffin", difficulty: "hard", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2009-2023", team: "Clippers/Pistons" }] },
    { name: "LaMarcus Aldridge", difficulty: "hard", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2006-2022", team: "Blazers/Spurs" }] },
    { name: "Kemba Walker", difficulty: "hard", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2011-2023", team: "Hornets/Celtics" }] },
    { name: "Rajon Rondo", difficulty: "hard", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2006-2022", team: "Celtics/Lakers" }] },
    { name: "Jarrett Allen", difficulty: "hard", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2017-Present", team: "Cavaliers/Nets" }] },

    // --- HARD (Role Players / Deep Cuts / Euro Stars) ---
    { name: "Austin Reaves", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2021-Present", team: "LA Lakers" }] },
    { name: "Alex Caruso", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2017-Present", team: "OKC/Bulls/Lakers" }] },
    { name: "Josh Hart", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2017-Present", team: "Knicks/Blazers/Pelicans/Lakers" }] },
    { name: "OG Anunoby", difficulty: "hard", status: "active", position: "Forvet", flag: "🇬🇧", nationality: "İngiltere", career: [{ years: "2017-Present", team: "Knicks/Raptors" }] },
    { name: "Mikal Bridges", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2018-Present", team: "Knicks/Nets/Suns" }] },
    { name: "Myles Turner", difficulty: "hard", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2015-Present", team: "Indiana Pacers" }] },
    { name: "Jaren Jackson Jr.", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2018-Present", team: "Memphis Grizzlies" }] },
    { name: "Desmond Bane", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2020-Present", team: "Memphis Grizzlies" }] },
    { name: "Anfernee Simons", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2018-Present", team: "Portland Trail Blazers" }] },
    { name: "Tyler Herro", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2019-Present", team: "Miami Heat" }] },
    { name: "Kyle Kuzma", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2017-Present", team: "Wizards/Lakers" }] },
    { name: "Jordan Poole", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2019-Present", team: "Wizards/Warriors" }] },
    { name: "D'Angelo Russell", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2015-Present", team: "Lakers/Wolves/Nets" }] },
    { name: "Fred VanVleet", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2016-Present", team: "Rockets/Raptors" }] },
    { name: "Dillon Brooks", difficulty: "hard", status: "active", position: "Forvet", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "2017-Present", team: "Rockets/Grizzlies" }] },
    { name: "Brook Lopez", difficulty: "hard", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2008-Present", team: "Bucks/Nets" }] },
    { name: "Al Horford", difficulty: "hard", status: "active", position: "Pivot", flag: "🇩🇴", nationality: "Dominik Cum.", career: [{ years: "2007-Present", team: "Boston Celtics" }] },
    { name: "Bobby Portis", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2015-Present", team: "Milwaukee Bucks" }] },
    { name: "Kevon Looney", difficulty: "hard", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2015-Present", team: "Golden State Warriors" }] },
    { name: "Ivica Zubac", difficulty: "hard", status: "active", position: "Pivot", flag: "🇭🇷", nationality: "Hırvatistan", career: [{ years: "2016-Present", team: "LA Clippers" }] },
    { name: "Andrew Bogut", difficulty: "hard", status: "retired", position: "Pivot", flag: "🇦🇺", nationality: "Avustralya", career: [{ years: "2005-2019", team: "Warriors/Bucks" }] },
    { name: "Buddy Hield", difficulty: "hard", status: "active", position: "Guard", flag: "🇧🇸", nationality: "Bahamalar", career: [{ years: "2016-Present", team: "Warriors/76ers/Pacers/Kings" }] },
    { name: "Harrison Barnes", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2012-Present", team: "Spurs/Kings/Mavs/Warriors" }] },
    { name: "Tobias Harris", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2011-Present", team: "Pistons/76ers/Clippers" }] },
    { name: "Clint Capela", difficulty: "hard", status: "active", position: "Pivot", flag: "🇨🇭", nationality: "İsviçre", career: [{ years: "2014-Present", team: "Hawks/Rockets" }] },
    { name: "Steven Adams", difficulty: "hard", status: "active", position: "Pivot", flag: "🇳🇿", nationality: "Yeni Zelanda", career: [{ years: "2013-Present", team: "Rockets/Grizzlies/OKC" }] },
    { name: "Jonas Valanciunas", difficulty: "hard", status: "active", position: "Pivot", flag: "🇱🇹", nationality: "Litvanya", career: [{ years: "2012-Present", team: "Wizards/Pelicans/Grizzlies/Raptors" }] },
    { name: "Nikola Vucevic", difficulty: "hard", status: "active", position: "Pivot", flag: "🇲🇪", nationality: "Karadağ", career: [{ years: "2011-Present", team: "Bulls/Magic" }] },
    { name: "Rui Hachimura", difficulty: "hard", status: "active", position: "Forvet", flag: "🇯🇵", nationality: "Japonya", career: [{ years: "2019-Present", team: "LA Lakers" }] },
    { name: "Deni Avdija", difficulty: "hard", status: "active", position: "Forvet", flag: "🇮🇱", nationality: "İsrail", career: [{ years: "2020-Present", team: "Blazers/Wizards" }] },
    { name: "Mike James", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2014-Present", team: "Monaco/Nets/Suns" }] },
    { name: "Edy Tavares", difficulty: "hard", status: "active", position: "Pivot", flag: "🇨🇻", nationality: "Yeşil Burun", career: [{ years: "2014-Present", team: "Real Madrid" }] },
    { name: "Sergio Llull", difficulty: "hard", status: "active", position: "Guard", flag: "🇪🇸", nationality: "İspanya", career: [{ years: "2007-Present", team: "Real Madrid" }] },
    { name: "Mario Hezonja", difficulty: "hard", status: "active", position: "Forvet", flag: "🇭🇷", nationality: "Hırvatistan", career: [{ years: "2015-Present", team: "Real Madrid/Knicks/Magic" }] },
    { name: "Dzanan Musa", difficulty: "hard", status: "active", position: "Forvet", flag: "🇧🇦", nationality: "Bosna Hersek", career: [{ years: "2018-Present", team: "Real Madrid/Nets" }] },
    { name: "Facundo Campazzo", difficulty: "hard", status: "active", position: "Guard", flag: "🇦🇷", nationality: "Arjantin", career: [{ years: "2014-Present", team: "Real Madrid/Nuggets" }] },
    { name: "Joe Ingles", difficulty: "hard", status: "active", position: "Guard", flag: "🇦🇺", nationality: "Avustralya", career: [{ years: "2014-Present", team: "Timberwolves/Bucks/Jazz" }] },
    { name: "Walter Tavares", difficulty: "hard", status: "active", position: "Pivot", flag: "🇨🇻", nationality: "Yeşil Burun", career: [{ years: "2014-Present", team: "Real Madrid" }] },
    { name: "Nikola Mirotic", difficulty: "hard", status: "active", position: "Forvet", flag: "🇪🇸", nationality: "İspanya", career: [{ years: "2014-Present", team: "Milano/Barcelona/Bulls" }] },
    { name: "Marco Belinelli", difficulty: "hard", status: "active", position: "Guard", flag: "🇮🇹", nationality: "İtalya", career: [{ years: "2007-Present", team: "Virtus Bologna/Spurs" }] },
 // Melli played in Fener. Removing.
    { name: "Daniel Hackett", difficulty: "hard", status: "active", position: "Guard", flag: "🇮🇹", nationality: "İtalya", career: [{ years: "2010-Present", team: "Virtus Bologna/CSKA" }] },
    { name: "Tomas Satoransky", difficulty: "hard", status: "active", position: "Guard", flag: "🇨🇿", nationality: "Çekya", career: [{ years: "2016-Present", team: "Barcelona/Wizards/Bulls" }] },
    { name: "Gabriel Deck", difficulty: "hard", status: "active", position: "Forvet", flag: "🇦🇷", nationality: "Arjantin", career: [{ years: "2018-Present", team: "Real Madrid/OKC Thunder" }] },
    { name: "Guerschon Yabusele", difficulty: "hard", status: "active", position: "Forvet", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2017-Present", team: "76ers/Real Madrid/Celtics" }] },
    { name: "Matthias Lessort", difficulty: "hard", status: "active", position: "Pivot", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2017-Present", team: "Panathinaikos/Partizan" }] },
    { name: "Kendrick Nunn", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2019-Present", team: "Panathinaikos/Lakers/Heat" }] },
    { name: "Lorenzo Brown", difficulty: "hard", status: "active", position: "Guard", flag: "🇪🇸", nationality: "İspanya", career: [{ years: "2013-Present", team: "Panathinaikos/Maccabi" }] },
    { name: "Willy Hernangomez", difficulty: "hard", status: "active", position: "Pivot", flag: "🇪🇸", nationality: "İspanya", career: [{ years: "2016-Present", team: "Barcelona/Pelicans/Knicks" }] },
    { name: "Juancho Hernangomez", difficulty: "hard", status: "active", position: "Forvet", flag: "🇪🇸", nationality: "İspanya", career: [{ years: "2016-Present", team: "Panathinaikos/Raptors/Nuggets" }] },
    { name: "Santi Aldama", difficulty: "hard", status: "active", position: "Forvet", flag: "🇪🇸", nationality: "İspanya", career: [{ years: "2021-Present", team: "Memphis Grizzlies" }] },
    { name: "Jose Alvarado", difficulty: "hard", status: "active", position: "Guard", flag: "🇵🇷", nationality: "Porto Riko", career: [{ years: "2021-Present", team: "New Orleans Pelicans" }] },

    // --- BATCH (NBA All-Stars & Legends) ---
    { name: "Franz Wagner", difficulty: "medium", status: "active", position: "Forvet", flag: "🇩🇪", nationality: "Almanya", career: [{ years: "2017-2019", team: "Alba Berlin" }, { years: "2021-Present", team: "Orlando Magic" }] },
    { name: "Jalen Suggs", difficulty: "medium", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2021-Present", team: "Orlando Magic" }] },
    { name: "Derrick White", difficulty: "medium", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2017-2022", team: "San Antonio Spurs" }, { years: "2022-Present", team: "Boston Celtics" }] },
    { name: "Jrue Holiday", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2009-2013", team: "Philadelphia 76ers" }, { years: "2013-2020", team: "New Orleans Pelicans" }, { years: "2020-2023", team: "Milwaukee Bucks" }, { years: "2023-Present", team: "Boston Celtics" }] },
    { name: "Aaron Gordon", difficulty: "medium", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2014-2021", team: "Orlando Magic" }, { years: "2021-Present", team: "Denver Nuggets" }] },
    { name: "Michael Porter Jr.", difficulty: "medium", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2018-Present", team: "Denver Nuggets" }] },
    { name: "Jalen Williams", difficulty: "medium", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2022-Present", team: "OKC Thunder" }] },
    { name: "Dejounte Murray", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2016-2022", team: "San Antonio Spurs" }, { years: "2022-2024", team: "Atlanta Hawks" }, { years: "2024-Present", team: "New Orleans Pelicans" }] },
    { name: "RJ Barrett", difficulty: "medium", status: "active", position: "Forvet", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "2019-2023", team: "New York Knicks" }, { years: "2023-Present", team: "Toronto Raptors" }] },
    { name: "Immanuel Quickley", difficulty: "medium", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2020-2023", team: "New York Knicks" }, { years: "2023-Present", team: "Toronto Raptors" }] },
    { name: "Allen Iverson", difficulty: "easy", status: "retired", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "1996-2006", team: "Philadelphia 76ers" }, { years: "2006-2008", team: "Denver Nuggets" }, { years: "2008-2009", team: "Detroit Pistons" }] },
    { name: "Dwight Howard", difficulty: "easy", status: "retired", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2004-2012", team: "Orlando Magic" }, { years: "2012-2013", team: "LA Lakers" }, { years: "2013-2016", team: "Houston Rockets" }, { years: "2019-2020", team: "LA Lakers (Champion)" }] },
    { name: "Amar'e Stoudemire", difficulty: "medium", status: "retired", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2002-2010", team: "Phoenix Suns" }, { years: "2010-2015", team: "New York Knicks" }] },
    { name: "Peja Stojakovic", difficulty: "medium", status: "retired", position: "Forvet", flag: "🇷🇸", nationality: "Sırbistan", career: [{ years: "1998-2006", team: "Sacramento Kings" }, { years: "2006-2010", team: "New Orleans Hornets" }, { years: "2011", team: "Dallas Mavericks" }] },
    { name: "Vlade Divac", difficulty: "medium", status: "retired", position: "Pivot", flag: "🇷🇸", nationality: "Sırbistan", career: [{ years: "1989-1996", team: "LA Lakers" }, { years: "1996-1998", team: "Charlotte Hornets" }, { years: "1998-2004", team: "Sacramento Kings" }] },
    { name: "Arvydas Sabonis", difficulty: "hard", status: "retired", position: "Pivot", flag: "🇱🇹", nationality: "Litvanya", career: [{ years: "1992-1995", team: "Real Madrid" }, { years: "1995-2001", team: "Portland Trail Blazers" }] },
    { name: "Chris Paul", difficulty: "easy", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2011-2017", team: "LA Clippers" }, { years: "2017-2019", team: "Houston Rockets" }, { years: "2020-2023", team: "Phoenix Suns" }, { years: "2024-Present", team: "San Antonio Spurs" }] },
    { name: "Khris Middleton", difficulty: "medium", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2013-Present", team: "Milwaukee Bucks" }] },
    { name: "Cam Thomas", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2021-Present", team: "Brooklyn Nets" }] },
    { name: "Nic Claxton", difficulty: "hard", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2019-Present", team: "Brooklyn Nets" }] },
    { name: "Josh Giddey", difficulty: "medium", status: "active", position: "Guard", flag: "🇦🇺", nationality: "Avustralya", career: [{ years: "2021-2024", team: "OKC Thunder" }, { years: "2024-Present", team: "Chicago Bulls" }] },
    { name: "Coby White", difficulty: "medium", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2019-Present", team: "Chicago Bulls" }] },
    { name: "Jalen Johnson", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2021-Present", team: "Atlanta Hawks" }] },
    { name: "Jalen Duren", difficulty: "hard", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2022-Present", team: "Detroit Pistons" }] },
    { name: "Ausar Thompson", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2023-Present", team: "Detroit Pistons" }] },
    { name: "Amen Thompson", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2023-Present", team: "Houston Rockets" }] },
    { name: "Jabari Smith Jr.", difficulty: "hard", status: "active", position: "Forvet", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2022-Present", team: "Houston Rockets" }] },
    { name: "Walker Kessler", difficulty: "hard", status: "active", position: "Pivot", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2022-Present", team: "Utah Jazz" }] },
    { name: "Keyonte George", difficulty: "hard", status: "active", position: "Guard", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2023-Present", team: "Utah Jazz" }] },
    { name: "Bilal Coulibaly", difficulty: "hard", status: "active", position: "Forvet", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2022-2023", team: "Metropolitans 92" }, { years: "2023-Present", team: "Washington Wizards" }] }
];
