const lolPlayers = [
    // --- LCK (Korea) ---
    { name: "Faker", difficulty: "easy", status: "active", position: "Mid", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2013-2019", team: "SK Telecom T1 (SKT)" }, { years: "2020-Present", team: "T1" }, { years: "2013, 2015, 2016, 2023, 2024", team: "5x World Champion" }] },
    { name: "Chovy", difficulty: "easy", status: "active", position: "Mid", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2018-2020", team: "Griffin / DB" }, { years: "2021", team: "Hanwha Life" }, { years: "2022-Present", team: "Gen.G" }, { years: "2024", team: "MSI Champion" }] },
    { name: "ShowMaker", difficulty: "easy", status: "active", position: "Mid", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2017-2018", team: "SANDBOX Gaming" }, { years: "2019-Present", team: "DAMWON / DPlus KIA" }, { years: "2020", team: "World Champion" }] },
    { name: "Canyon", difficulty: "easy", status: "active", position: "Jungle", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2019-2023", team: "DAMWON / DPlus KIA" }, { years: "2024-Present", team: "Gen.G" }, { years: "2020", team: "World Champion" }] },
    { name: "Viper", difficulty: "easy", status: "active", position: "ADC", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2019-2021", team: "Edward Gaming" }, { years: "2022-Present", team: "HLE" }, { years: "2021", team: "World Champion (EDG)" }] },
    { name: "Keria", difficulty: "easy", status: "active", position: "Support", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2021-Present", team: "T1" }, { years: "2023, 2024", team: "2x World Champion" }] },
    { name: "Gumayusi", difficulty: "easy", status: "active", position: "ADC", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2021-Present", team: "T1" }, { years: "2023, 2024", team: "2x World Champion" }] },
    { name: "Zeus", difficulty: "easy", status: "active", position: "Top", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2022-2024", team: "T1" }, { years: "2023", team: "World Champion" }, { years: "2025-Present", team: "HLE" }] },

    // --- LPL (China) ---
    { name: "Knight", difficulty: "easy", status: "active", position: "Mid", flag: "🇨🇳", nationality: "Çin", career: [{ years: "2018-2019", team: "Invictus Gaming" }, { years: "2020-2023", team: "JDG Esports" }, { years: "2023", team: "MSI Champion" }, { years: "2024-Present", team: "BLG" }] },
    { name: "Bin", difficulty: "easy", status: "active", position: "Top", flag: "🇨🇳", nationality: "Çin", career: [{ years: "2020-Present", team: "Bilibili Gaming" }, { years: "2021, 2022", team: "2x MSI Champion" }] },
    { name: "JackeyLove", difficulty: "easy", status: "active", position: "ADC", flag: "🇨🇳", nationality: "Çin", career: [{ years: "2017-2019", team: "Invictus Gaming" }, { years: "2018", team: "World Champion (iG)" }, { years: "2020-Present", team: "Top Esports (TES)" }] },
    { name: "Meiko", difficulty: "easy", status: "active", position: "Support", flag: "🇨🇳", nationality: "Çin", career: [{ years: "2014-2023", team: "Edward Gaming" }, { years: "2021", team: "World Champion (EDG)" }, { years: "2024-Present", team: "Top Esports (TES)" }] },
    { name: "Rookie", difficulty: "easy", status: "active", position: "Mid", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2015-2023", team: "Invictus Gaming" }, { years: "2018", team: "World Champion (iG)" }, { years: "2024-Present", team: "NIP" }] },
    { name: "Uzi", difficulty: "easy", status: "retired", position: "ADC", flag: "🇨🇳", nationality: "Çin", career: [{ years: "2012-2019", team: "Royal Never Give Up (RNG)" }, { years: "2018", team: "MSI Champion" }, { years: "2020-2022", team: "BLG (brief returns)" }] },

    // --- LEC/LCS (West) ---
    { name: "Caps", difficulty: "easy", status: "active", position: "Mid", flag: "🇩🇰", nationality: "Danimarka", career: [{ years: "2017-2018", team: "Fnatic" }, { years: "2019-Present", team: "G2 Esports" }, { years: "2019", team: "MSI Champion" }] },
    { name: "Jankos", difficulty: "easy", status: "active", position: "Jungle", flag: "🇵🇱", nationality: "Polonya", career: [{ years: "2016-2017", team: "H2K Gaming" }, { years: "2018-2022", team: "G2 Esports" }, { years: "2019", team: "MSI Champion" }, { years: "2023-Present", team: "Team Heretics" }] },
    { name: "Rekkles", difficulty: "easy", status: "active", position: "ADC/Support", flag: "🇸🇪", nationality: "İsveç", career: [{ years: "2012-2020", team: "Fnatic" }, { years: "2021", team: "G2 Esports" }, { years: "2022-2023", team: "Karmine Corp" }, { years: "2024-Present", team: "T1 Academy" }] },
    { name: "Perkz", difficulty: "easy", status: "active", position: "Mid/ADC", flag: "🇭🇷", nationality: "Hırvatistan", career: [{ years: "2015-2020", team: "G2 Esports" }, { years: "2019", team: "MSI Champion" }, { years: "2021", team: "Cloud9" }, { years: "2022-2023", team: "Team Vitality" }, { years: "2024-Present", team: "Team Heretics" }] },
    { name: "Bjergsen", difficulty: "easy", status: "retired", position: "Mid", flag: "🇩🇰", nationality: "Danimarka", career: [{ years: "2013-2020", team: "TSM" }, { years: "2021", team: "Team Liquid (Coach)" }, { years: "2022-2023", team: "TSM" }] },
    { name: "Doublelift", difficulty: "easy", status: "retired", position: "ADC", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2011-2015", team: "CLG" }, { years: "2015-2017", team: "TSM" }, { years: "2017-2018", team: "CLG" }, { years: "2018-2020", team: "TSM / Team Liquid" }] },
    { name: "Impact", difficulty: "easy", status: "active", position: "Top", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2012-2013", team: "SKT T1" }, { years: "2013", team: "World Champion" }, { years: "2014-2017", team: "Team Impulse / Immortals" }, { years: "2018-Present", team: "TL / EG / FlyQuest" }] },
    { name: "Jensen", difficulty: "easy", status: "active", position: "Mid", flag: "🇩🇰", nationality: "Danimarka", career: [{ years: "2014-2015", team: "CLG" }, { years: "2016-2018", team: "Cloud9" }, { years: "2019-2021", team: "Team Liquid" }, { years: "2022-2023", team: "Cloud9" }, { years: "2024-Present", team: "Dignitas / FlyQuest" }] },
    { name: "CoreJJ", difficulty: "easy", status: "active", position: "Support", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2016-2017", team: "Samsung Galaxy" }, { years: "2017", team: "World Champion (SSG)" }, { years: "2019-Present", team: "Team Liquid" }] },
    { name: "Bwipo", difficulty: "easy", status: "active", position: "Top/Jungle", flag: "🇧🇪", nationality: "Belçika", career: [{ years: "2018-2021", team: "Fnatic" }, { years: "2022", team: "Team Liquid" }, { years: "2023-Present", team: "FlyQuest" }] },
];

const csPlayers = [
    { name: "s1mple", difficulty: "easy", status: "active", position: "AWP", flag: "🇺🇦", nationality: "Ukrayna", career: [{ years: "2012-2015", team: "FlipSid3 / HellRaisers" }, { years: "2015-2016", team: "Team Liquid" }, { years: "2016-Present", team: "Natus Vincere" }, { years: "2021", team: "PGL Major Champion" }, { years: "2024", team: "Team Falcons (loan)" }] },
    { name: "ZywOo", difficulty: "easy", status: "active", position: "AWP", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2018-Present", team: "Team Vitality" }, { years: "2022, 2023", team: "2x HLTV #1" }, { years: "2023", team: "Paris Major Finalist" }] },
    { name: "NiKo", difficulty: "easy", status: "active", position: "Rifler", flag: "🇧🇦", nationality: "Bosna", career: [{ years: "2014-2016", team: "mousesports" }, { years: "2016-2020", team: "FaZe Clan" }, { years: "2020-Present", team: "G2 Esports" }, { years: "2023", team: "IEM Cologne Champion" }] },
    { name: "m0NESY", difficulty: "easy", status: "active", position: "AWP", flag: "🇷🇺", nationality: "Rusya", career: [{ years: "2021-2022", team: "G2 Esports Academy" }, { years: "2022-Present", team: "G2 Esports" }, { years: "2024", team: "IEM Dallas MVP" }] },
    { name: "donk", difficulty: "easy", status: "active", position: "Rifler", flag: "🇷🇺", nationality: "Rusya", career: [{ years: "2022-2023", team: "Spirit Academy" }, { years: "2023-Present", team: "Team Spirit" }, { years: "2024", team: "IEM Katowice MVP" }] },
    { name: "device", difficulty: "easy", status: "active", position: "AWP", flag: "🇩🇰", nationality: "Danimarka", career: [{ years: "2014-2021", team: "Astralis" }, { years: "2016, 2017, 2018, 2019", team: "4x Major Champion" }, { years: "2021-2022", team: "NIP" }, { years: "2022-Present", team: "Astralis" }] },
    { name: "karrigan", difficulty: "easy", status: "active", position: "IGL", flag: "🇩🇰", nationality: "Danimarka", career: [{ years: "2014-2017", team: "Astralis" }, { years: "2017-2020", team: "FaZe Clan" }, { years: "2021-2022", team: "mousesports / MOUZ" }, { years: "2022-Present", team: "FaZe Clan" }, { years: "2022", team: "IEM Katowice Champion" }] },
    { name: "Twistzz", difficulty: "easy", status: "active", position: "Rifler", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "2018-2020", team: "Team Liquid" }, { years: "2021-2023", team: "FaZe Clan" }, { years: "2022", team: "Major Champion (PGL Antwerp)" }, { years: "2024-Present", team: "Team Liquid" }] },
    { name: "ropz", difficulty: "easy", status: "active", position: "Rifler", flag: "🇪🇪", nationality: "Estonya", career: [{ years: "2019-2022", team: "mousesports / MOUZ" }, { years: "2022-Present", team: "FaZe Clan" }, { years: "2022", team: "Major Champion (PGL Antwerp)" }] },
    { name: "electronic", difficulty: "easy", status: "active", position: "Rifler", flag: "🇷🇺", nationality: "Rusya", career: [{ years: "2017-2023", team: "Natus Vincere" }, { years: "2021", team: "PGL Major Stockholm Champion" }, { years: "2024-Present", team: "G2 Esports" }] },
    { name: "GeT_RiGhT", difficulty: "easy", status: "retired", position: "Rifler", flag: "🇸🇪", nationality: "İsveç", career: [{ years: "2007-2009", team: "Fnatic" }, { years: "2009-2011", team: "SK Gaming" }, { years: "2012-2019", team: "NIP" }, { years: "2012", team: "87-0 Map Streak" }] },
    { name: "f0rest", difficulty: "easy", status: "retired", position: "Rifler", flag: "🇸🇪", nationality: "İsveç", career: [{ years: "2007-2009", team: "Fnatic" }, { years: "2009-2012", team: "SK Gaming" }, { years: "2012-2019", team: "NIP" }, { years: "2019-2021", team: "Dignitas / Dignitas" }] },
    { name: "FalleN", difficulty: "easy", status: "active", position: "IGL", flag: "🇧🇷", nationality: "Brezilya", career: [{ years: "2013-2015", team: "LG Esports" }, { years: "2016", team: "SK Gaming" }, { years: "2016", team: "2x Major Champion" }, { years: "2018-2020", team: "MiBR" }, { years: "2021-2022", team: "Complexity / FalleN's Army" }, { years: "2023-Present", team: "FURIA" }] },
    { name: "coldzera", difficulty: "easy", status: "active", position: "Rifler", flag: "🇧🇷", nationality: "Brezilya", career: [{ years: "2014-2018", team: "LG / SK Gaming" }, { years: "2016, 2017", team: "2x Major Champion" }, { years: "2016, 2017", team: "2x HLTV #1" }, { years: "2018-2019", team: "FaZe Clan" }, { years: "2020", team: "MiBR" }, { years: "2021-Present", team: "paiN Gaming" }] },
    { name: "kennyS", difficulty: "easy", status: "retired", position: "AWP", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2012-2014", team: "VeryGames / LDLC" }, { years: "2015-2016", team: "Team EnVyUs" }, { years: "2015", team: "MLG Columbus Major MVP" }, { years: "2016-2021", team: "G2 Esports" }] },
];

const valorantPlayers = [
    { name: "Boaster", difficulty: "easy", status: "active", position: "IGL", flag: "🇬🇧", nationality: "İngiltere", career: [{ years: "2021-Present", team: "Fnatic" }, { years: "2023", team: "EMEA Champions (2x Trophy)" }] },
    { name: "TenZ", difficulty: "easy", status: "retired", position: "Duelist", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "2020", team: "Cloud9" }, { years: "2021-2024", team: "Sentinels" }, { years: "2021", team: "Reykjavik MVP" }] },
    { name: "aspas", difficulty: "easy", status: "active", position: "Duelist", flag: "🇧🇷", nationality: "Brezilya", career: [{ years: "2021-2023", team: "LOUD" }, { years: "2022", team: "World Champion (LOUD)" }, { years: "2024-Present", team: "Leviatán" }] },
    { name: "Chronicle", difficulty: "easy", status: "active", position: "Flex", flag: "🇷🇺", nationality: "Rusya", career: [{ years: "2021-2022", team: "Acend / FPX" }, { years: "2023", team: "Team Liquid" }, { years: "2023-Present", team: "Fnatic" }] },
    { name: "nAts", difficulty: "easy", status: "active", position: "Sentinel", flag: "🇷🇺", nationality: "Rusya", career: [{ years: "2021-2022", team: "Gambit Esports" }, { years: "2022-2023", team: "Team Spirit" }, { years: "2021", team: "Masters Berlin MVP" }, { years: "2023-Present", team: "Team Liquid" }] },
    { name: "Derke", difficulty: "easy", status: "active", position: "Duelist", flag: "🇫🇮", nationality: "Finlandiya", career: [{ years: "2021-2024", team: "Fnatic" }, { years: "2025-Present", team: "Team Vitality" }] },
    { name: "FNS", difficulty: "easy", status: "active", position: "IGL", flag: "🇨🇦", nationality: "Kanada", career: [{ years: "2021-2022", team: "OpTic Gaming" }, { years: "2022", team: "Masters Champ" }, { years: "2023-2024", team: "NRG Esports" }, { years: "2025-Present", team: "NRG / Cloud9" }] },
    { name: "Demon1", difficulty: "easy", status: "active", position: "Duelist", flag: "🇺🇸", nationality: "ABD", career: [{ years: "2022-2023", team: "Evil Geniuses (EG)" }, { years: "2023", team: "World Champion & MVP" }, { years: "2024-Present", team: "100 Thieves" }] },
    { name: "ZmjjKK", difficulty: "easy", status: "active", position: "Duelist", flag: "🇨🇳", nationality: "Çin", career: [{ years: "2023-Present", team: "Edward Gaming (EDG)" }, { years: "2024", team: "Champions Seoul MVP" }] },
    { name: "Sacy", difficulty: "easy", status: "retired", position: "Initiator", flag: "🇧🇷", nationality: "Brezilya", career: [{ years: "2021-2023", team: "LOUD" }, { years: "2022", team: "World Champion (LOUD)" }, { years: "2023-2024", team: "Sentinels" }, { years: "2024", team: "VCT Madrid Champion" }] },
    { name: "Saadhak", difficulty: "easy", status: "active", position: "IGL", flag: "🇦🇷", nationality: "Arjantin", career: [{ years: "2021-2024", team: "LOUD" }, { years: "2022", team: "World Champion (LOUD)" }, { years: "2025-Present", team: "Cloud9" }] },
    { name: "MaKo", difficulty: "easy", status: "active", position: "Controller", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2021-2022", team: "Vision Strikers" }, { years: "2022", team: "World Champion (DRX)" }, { years: "2022-Present", team: "DRX" }] },
    { name: "Forsaken", difficulty: "easy", status: "active", position: "Flex", flag: "🇮🇩", nationality: "Endonezya", career: [{ years: "2021-Present", team: "Paper Rex" }, { years: "2022-2024", team: "Pacific League Finalist" }] },
    { name: "Jinggg", difficulty: "easy", status: "active", position: "Duelist", flag: "🇸🇬", nationality: "Singapur", career: [{ years: "2021-Present", team: "Paper Rex" }, { years: "2022-2024", team: "Pacific League Finalist" }] },
    { name: "Leo", difficulty: "easy", status: "active", position: "Initiator", flag: "🇸🇪", nationality: "İsveç", career: [{ years: "2022", team: "Fnatic Academy" }, { years: "2023-Present", team: "Fnatic" }, { years: "2023", team: "LOCK//IN MVP" }] },

    // --- BATCH (Global Legends & Stars) ---
    // LoL
    { name: "Peyz", difficulty: "medium", status: "active", position: "ADC", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2020-2022", team: "Gen.G Academy" }, { years: "2023-Present", team: "Gen.G" }, { years: "2024", team: "MSI Champion" }] },
    { name: "Lehends", difficulty: "medium", status: "active", position: "Support", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2018-2019", team: "Griffin" }, { years: "2022", team: "Gen.G" }, { years: "2024-Present", team: "Gen.G" }, { years: "2024", team: "MSI Champion" }] },
    { name: "Kiin", difficulty: "medium", status: "active", position: "Top", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2018-2022", team: "Afreeca Freecs" }, { years: "2024-Present", team: "Gen.G" }, { years: "2024", team: "MSI Champion" }] },
    { name: "Xiaohu", difficulty: "easy", status: "active", position: "Mid/Top", flag: "🇨🇳", nationality: "Çin", career: [{ years: "2015-2022", team: "RNG" }, { years: "2023-Present", team: "WBG" }, { years: "2018, 2021, 2022", team: "3x MSI Champion" }] },
    { name: "TheShy", difficulty: "easy", status: "retired", position: "Top", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2017-2021", team: "Invictus Gaming" }, { years: "2018", team: "World Champion" }, { years: "2022-2023", team: "WBG" }] },
    { name: "Scout", difficulty: "easy", status: "active", position: "Mid", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2015", team: "SKT T1" }, { years: "2016-2022", team: "EDG" }, { years: "2021", team: "World Champion & MVP" }, { years: "2023-Present", team: "LNG" }] },
    { name: "Ruler", difficulty: "easy", status: "active", position: "ADC", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2016-2017", team: "Samsung Galaxy" }, { years: "2017", team: "World Champion & MVP" }, { years: "2018-2022", team: "Gen.G" }, { years: "2023-Present", team: "JDG" }] },
    { name: "Kanavi", difficulty: "easy", status: "active", position: "Jungle", flag: "🇰🇷", nationality: "Güney Kore", career: [{ years: "2019-Present", team: "JDG" }, { years: "2023", team: "MSI Champion" }] },
    { name: "Hans Sama", difficulty: "medium", status: "active", position: "ADC", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2016-2019", team: "Misfits" }, { years: "2020-2021", team: "Rogue" }, { years: "2022", team: "Team Liquid" }, { years: "2023-Present", team: "G2 Esports" }] },
    { name: "Mikyx", difficulty: "medium", status: "active", position: "Support", flag: "🇸🇮", nationality: "Slovenya", career: [{ years: "2016-2017", team: "Splyce" }, { years: "2019-2021", team: "G2 Esports" }, { years: "2023-Present", team: "G2 Esports" }] },

    // CS
    { name: "rain", difficulty: "medium", status: "active", position: "Rifler", flag: "🇳🇴", nationality: "Norveç", career: [{ years: "2016-Present", team: "FaZe Clan" }, { years: "2022", team: "Major Champion & MVP" }] },
    { name: "broky", difficulty: "medium", status: "active", position: "AWP", flag: "🇱🇻", nationality: "Letonya", career: [{ years: "2019-Present", team: "FaZe Clan" }, { years: "2022", team: "Major Champion" }] },
    { name: "frozen", difficulty: "medium", status: "active", position: "Rifler", flag: "🇸🇰", nationality: "Slovakya", career: [{ years: "2019-2023", team: "MOUZ" }, { years: "2023-Present", team: "FaZe Clan" }] },
    { name: "YEKINDAR", difficulty: "medium", status: "active", position: "Rifler", flag: "🇱🇻", nationality: "Letonya", career: [{ years: "2020-2022", team: "Virtus.pro / Outsidears" }, { years: "2022-Present", team: "Team Liquid" }] },
    { name: "shox", difficulty: "easy", status: "retired", position: "Rifler", flag: "🇫🇷", nationality: "Fransa", career: [{ years: "2013-2014", team: "VeryGames / Titan" }, { years: "2014-2015", team: "LDLC / EnVyUs" }, { years: "2016-2019", team: "G2 Esports" }, { years: "2019-2021", team: "Team Vitality" }] },
    { name: "olofmeister", difficulty: "easy", status: "retired", position: "Rifler", flag: "🇸🇪", nationality: "İsveç", career: [{ years: "2014-2017", team: "Fnatic" }, { years: "2015", team: "2x Major Champion" }, { years: "2017-2021", team: "FaZe Clan" }] },
    { name: "JW", difficulty: "medium", status: "retired", position: "AWP/Rifler", flag: "🇸🇪", nationality: "İsveç", career: [{ years: "2013-2021", team: "Fnatic" }, { years: "2013, 2015", team: "3x Major Champion" }] },
    { name: "KRIMZ", difficulty: "medium", status: "active", position: "Rifler", flag: "🇸🇪", nationality: "İsveç", career: [{ years: "2014-Present", team: "Fnatic" }, { years: "2015", team: "2x Major Champion" }] },

    // Valorant
    { name: "Benjyfishy", difficulty: "medium", status: "active", position: "Sentinel/Duelist", flag: "🇬🇧", nationality: "İngiltere", career: [{ years: "2022-2023", team: "Enterprise" }, { years: "2023-Present", team: "Team Heretics" }] },
    { name: "Boo", difficulty: "hard", status: "active", position: "IGL", flag: "🇱🇹", nationality: "Litvanya", career: [{ years: "2022", team: "G2 Esports" }, { years: "2024-Present", team: "Team Heretics" }] },
    { name: "Miniboo", difficulty: "hard", status: "active", position: "Duelist", flag: "🇱🇹", nationality: "Litvanya", career: [{ years: "2024-Present", team: "Team Heretics" }] },
    { name: "Less", difficulty: "medium", status: "active", position: "Sentinel", flag: "🇧🇷", nationality: "Brezilya", career: [{ years: "2022-2024", team: "LOUD" }, { years: "2022", team: "World Champion" }, { years: "2025-Present", team: "Team Vitality" }] },
    { name: "heat", difficulty: "hard", status: "active", position: "Duelist", flag: "🇧🇷", nationality: "Brezilya", career: [{ years: "2021-2022", team: "Vivo Keyd" }, { years: "2023", team: "MIBR" }, { years: "2024-Present", team: "KRÜ Esports" }] },
    { name: "Sayf", difficulty: "medium", status: "active", position: "Duelist/Flex", flag: "🇸🇪", nationality: "İsveç", career: [{ years: "2021-2022", team: "Guild Esports" }, { years: "2023", team: "Team Liquid" }, { years: "2024-Present", team: "Team Vitality" }] }
];

/**
 * Audit Note: 
 * All Turkish players (XANTARES, woxic, cNed, Alfjer, etc.) and Turkish league mentions have been purged 
 * to maintain a strictly global focus as requested.
 * Last updated: April 2026 - Full career histories with years added for all players.
 */
